Send picture from Pi to iPhone
Capstone-Projects-2022-Fall/capstone-project-rear-rider pull request #29
Opened 2022-11-06 07:11 UTC by calin-pescaru

2022-11-11 20:29 UTC, calin-pescaru commented
This PR bring the functionality of sending a picture from the RPi to the iPhone app over Bluetooth.

The way it works is as follows:
- in RiderView.swift there is a temporary button that initiates the transfer
- once the button is pushed, the RPi will activate the camera, take a picture, and save the data in a buffer in memory
- then the picture will be split into 512-byte packets
- the first piece of information that is sent to the iPhone is the picture size and the number of packets
- then the iPhone will request each packet in turn until there's no more packets left
- once all the packets are received, the data will be converted into an UIImage which in turn will be converted into a SwiftUI Image

Shortcomings:
- the transfer takes too much time for our purpose, about 8 seconds
- so far the algorithm doesn't check if any packets were missed
- if the Bluetooth connection is lost during transfer, the app on the iPhone and the app on the RPi need to be restarted

TODO:
- try to improve the transfer time by changing the resolution, quality, etc. of the picture and/or look into compression
- fix the above shortcomings

2022-11-12 17:21 UTC, bobby-palko requested changes
Looks good! Left a couple small improvements for ya. Also, please remove any commented out code 👍🏻

2022-11-12 17:21 UTC, bobby-palko commented on rear_rider_device/rear_rider_bluetooth_server/src/services/hello_world.py
> +        self.packet_size = 512
I would make the packet size a constant like you are with the uuid:

```suggestion
    TEST_CHRC_UUID = 'cd41b278-6254-4c89-9cd1-fd2578ab8abb'
    PACKET_SIZE = 512 # bytes

    def __init__(self, bus, index, service):
        Characteristic.__init__(
                self, bus, index,
                self.TEST_CHRC_UUID,
                ['read', 'write'],
                service)
        
        self.first_time = True # first time send the size of pic and the number of packets
        self.packets = 0
        self.packet_size = PACKET_SIZE
```

2022-11-12 17:21 UTC, bobby-palko commented on rear_rider_device/rear_rider_bluetooth_server/src/services/hello_world.py
> +        #self.f = open('/home/pi/log.txt', 'a') # for debugging
If this is for debugging please either set a log level where this would record to a debug log. Otherwise there's no reason to keep it commented out

2022-11-12 17:21 UTC, bobby-palko commented on rear_rider_device/rear_rider_bluetooth_server/src/services/hello_world.py
> +            #self.write_log('Picture sent')
like here. looks like this writes to a log, but is commented out

2022-11-12 17:21 UTC, bobby-palko commented on rear_rider_device/rear_rider_bluetooth_server/src/services/hello_world.py
> +            if self.packets % self.buff_size != 0: # if the division has remainder add one more packet
Any non-zero number is a truthy value in python. You should be able to simplify this to omit the 0 check:

```suggestion
            if self.packets % self.buff_size: # if the division has remainder add one more packet
```

2022-11-12 17:21 UTC, bobby-palko commented on rear_rider_device/rear_rider_bluetooth_server/src/services/hello_world.py
> +                end = end + self.packet_size # if it doesn't work change the last packet to buff_size - start
If you make the packet size a constant, you don't need a property on the `self` regarding it (unless it were to ever be modified). Then you can just use the constant here, as well as anywhere else you need to use that value. Using the constant over a property on self prevents other code from accidentally overwriting it (again, unless it's to be modified)
```suggestion
            end = self.packet_size
            
            # split self.data into a list
            for i in range(0, self.packets):
                self.dataList.append(self.data.getvalue()[start:end])
                #b.write(self.dataList[i])
                start = start + PACKET_SIZE
                end = end + PACKET_SIZE # if it doesn't work change the last packet to buff_size - start
```

2022-11-12 17:21 UTC, bobby-palko commented on rear_rider_device/rear_rider_bluetooth_server/src/services/hello_world.py
> +                end = end + self.packet_size # if it doesn't work change the last packet to buff_size - start
you can add a third arg to `range` to auto increment by the packet size:
```suggestion
            # split self.data into a list
            for i in range(0, self.packets, PACKET_SIZE):
                self.dataList.append(self.data.getvalue()[i:i+PACKET_SIZE])
```

This removes the need for variables external to the loop and reduces the extra overhead to keep track of them

2022-11-12 20:05 UTC, calin-pescaru commented
> Looks good! Left a couple small improvements for ya. Also, please remove any commented out code 👍🏻

2022-11-12 20:07 UTC, calin-pescaru commented
> Looks good! Left a couple small improvements for ya. Also, please remove any commented out code 👍🏻

Thanks for the input. If I can manage to bring down the file size significantly maybe this code will not be needed anymore. If we're still gonna use it then I will make the requested changes.

2022-11-14 19:36 UTC, jon-dez approved these changes
tested

2022-11-15 02:45 UTC, bobby-palko approved these changes

2022-11-15 02:45 UTC, merged